Update ciValidate.yml

diff --git a/.github/workflows/ciValidate.yml b/.github/workflows/ciValidate.yml
--- a/.github/workflows/ciValidate.yml
+++ b/.github/workflows/ciValidate.yml
@@ -65,18 +65,18 @@ jobs:
         run: |
           echo "diffedSfFiles=$(git diff --name-only --diff-filter=d HEAD~ -- **/*.{cls,cmp,component,css,html,js,json,page,trigger,xml} **/{aura,lwc}/**/*.js | tr '\n' ' ')" >> $GITHUB_OUTPUT
 
-      - name: Run Salesforce Code Analyzer
-        id: run-code-analyzer
-        uses: forcedotcom/run-code-analyzer@v1
-        if: steps.getDiff.outputs.diffedSfFiles != ''
-        with:
-          run-command: run
-          run-arguments: --normalize-severity --target ${{ steps.getDiff.outputs.diffedSfFiles }} --outfile results.html
-          results-artifact-name: salesforce-code-analyzer-results
+      # - name: Run Salesforce Code Analyzer
+      #   id: run-code-analyzer
+      #   uses: forcedotcom/run-code-analyzer@v1
+      #   if: steps.getDiff.outputs.diffedSfFiles != ''
+      #   with:
+      #     run-command: run
+      #     run-arguments: --normalize-severity --target ${{ steps.getDiff.outputs.diffedSfFiles }} --outfile results.html
+      #     results-artifact-name: salesforce-code-analyzer-results
 
-      - name: Check the Salesforce Code Analyzer outputs to determine whether to fail
-        if: |
-          steps.run-code-analyzer.outputs.exit-code > 0 ||
-          steps.run-code-analyzer.outputs.num-sev1-violations > 0 ||
-          steps.run-code-analyzer.outputs.num-violations > 10
-        run: exit 1
+      # - name: Check the Salesforce Code Analyzer outputs to determine whether to fail
+      #   if: |
+      #     steps.run-code-analyzer.outputs.exit-code > 0 ||
+      #     steps.run-code-analyzer.outputs.num-sev1-violations > 0 ||
+      #     steps.run-code-analyzer.outputs.num-violations > 10
+      #   run: exit 1
